### ISSUE TITLE
Emerald tool recipes still registered when emerald tools are disabled

### ISSUE THREAD

**Issue by dninemfive** [bdani0717/fabric-hammers-1.20#5]
This mod still tries to register the recipes for emerald tools when the config option to disable them is set, leading to non-fatal errors when launching the game.

i'm not entirely familiar with registering recipes using Fabric, but i believe to fix this you could [add a recipe provider](https://fabricmc.net/wiki/tutorial:datagen_setup) to [your data generator](https://github.com/bdani0717/fabric-hammers-1.20/blob/master/src/main/java/net/w/fabrichammers/FabricHammersDataGenerator.java) and create an override of `generateRecipes()` which checks the [`isEnableEmeradlTools`](https://github.com/bdani0717/fabric-hammers-1.20/blob/master/src/main/java/net/w/fabrichammers/config/Config.java#L73) config value.

**Comment by bdani0717** [comment]
added recipe provider with condition
