### ISSUE TITLE
Any Chance for Excavator Mod?

### ISSUE THREAD

**Issue by Daihok41** [bdani0717/fabric-hammers-1.20#7]
Like Title says any chance you will make an excavator mod as well? Love the hammer one the Hammers actually work like they should compared to other hammer mods on fabric.

**Comment by bdani0717** [comment]
added in 1.2

**Comment by Daihok41** [comment]
Your Awesome! Also another suggestion maybe make the outline of blocks being mined more visible? Just a suggestion. This mod is by far the best out there for more vanillish on Fabric the other hammer/excavator mods are so buggy in the way they break blocks.
